# Generated by Django 3.0.4 on 2020-04-27 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventType',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='baby_id',
            new_name='baby',
        ),
    ]
