# Generated by Django 3.0.4 on 2020-04-27 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_baby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baby',
            old_name='parent_id',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='user_id',
            new_name='user',
        ),
    ]
