# Generated by Django 3.0.4 on 2020-04-27 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0009_auto_20200427_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baby',
            options={'permissions': (('see_baby', 'See baby'),)},
        ),
    ]
